WebAppQuiz/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebAppQuiz.Models;
using WebAppQuiz.ViewModel;

namespace WebAppQuiz.Controllers
{
    public class QuizController : Controller
    {
        private QuizDBEntities objQuizDbEntities;


        public QuizController()
        {
            objQuizDbEntities = new QuizDBEntities();
        }
        public ActionResult Index()
        {
            QuizCategoryViewModel objQuizCategoryViewModel = new QuizCategoryViewModel();   
            objQuizCategoryViewModel.ListOfCategory = (from obj in objQuizDbEntities.Categories
                                                       select new SelectListItem()
                                                       {
                                                           Value = obj.CategoryId.ToString(),
                                                           Text = obj.CategoryName

                                                       }).ToList();
            return View(objQuizCategoryViewModel);
        }

        [HttpPost]
        public ActionResult Index(string CandidateName,int CategoryId)
        {
            User objUser = new User();
            objUser.UserName = CandidateName;
            objUser.LoginTime = DateTime.Now;
            objUser.CategoryId = CategoryId;
            objQuizDbEntities.Users.Add(objUser);
            objQuizDbEntities.SaveChanges();

            Session["CandidateName"] = CandidateName;
            Session["CategoryId"] = CategoryId;
            return View("QuestionIndex"); 

        }

        public PartialViewResult UserQuestionAnswer()
        {
            int pageSize = 1;
            int pageNumber = 0;
            int CategoryId = Convert.ToInt32(Session["CategoryId"]); 
            if(Session["CadQuestionAnswer"] == null)
            {
                pageNumber = pageNumber + 1;
            }
            else
            {
                List<CandidateAnswer> canAnswer = Session["CadQuestionAnswer"] as List<CandidateAnswer>;
                pageNumber = canAnswer.Count + 1;
            }
            List<Question> listOfQuestion = new List<Question>();
            listOfQuestion = objQuizDbEntities.Questions.Where(model => model.CategoryId == CategoryId).ToList();

            QuizQuestionAnswerViewModel objAnswerViewModel = new QuizQuestionAnswerViewModel();
            Question objQuestion = new Question();
            objQuestion = listOfQuestion.Skip((pageNumber - 1) * pageSize).Take(pageSize).FirstOrDefault();

            objAnswerViewModel.QuestionId = objQuestion.QuestionId;
            objAnswerViewModel.QuestionName = objQuestion.QuestionName;
            objAnswerViewModel.ListOfQuizOptions = (from obj in objQuizDbEntities.Options
                                                    where obj.QuestionId == objQuestion.QuestionId
                                                    select new QuizOption()
                                                    {
                                                        OptionName = obj.OptionName,
                                                        OptionId = obj.OptionId
                                                    }).ToList();
            return PartialView("QuizQuestionOptions", "data");
        }

    }
}

WebAppQuiz/Views/Quiz/Index.cshtml
@model WebAppQuiz.ViewModel.QuizCategoryViewModel   
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "Quiz", FormMethod.Post))
{
    @Html.ValidationSummary(true, null, new { @class="text-danger"})
<div class="container">
    <div class="form-group">
        @Html.LabelFor(model => model.CandidateName)
        @Html.TextBoxFor(model => model.CandidateName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId)
        @Html.DropDownListFor(model => model.CategoryId, Model.ListOfCategory, new { @class = "form-control", @id = "ddCategoryId" })
       @*list of category'i returnde döndürdmediğim için hata veriyormuş.*@
        @*çözüldü 5:00 10/14/2020*@
    </div>

    <input type="submit" name="Submit" value="Submit" class="btn btn-primary" />
</div>
}

WebAppQuiz/Views/Quiz/QuestionIndex.cshtml
@{
    ViewBag.Title = "QuestionIndex";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

    })


    function LoadQuestion() {
        $.ajax({
            async: true,
            type: 'GET',
            dataType: 'HTML',
            contentType: 'application/json; charset=utf-8',
            url: '/Quiz/UserQuestionAnswer',
            data: QuestionAnswer,
            success: function (data) {
                $("#divQuestionOption".html(data);
            },
             error: function (data) {
                alert(data);
            }
        });
    }
</script>